name: Generate Changes

on:
  workflow_call:
    outputs:
      java:
        value: ${{ jobs.changes.outputs.java }}
      openframe-frontend-core:
        value: ${{ jobs.changes.outputs.openframe-frontend-core }}


jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      openframe-frontend-core: ${{ steps.filter.outputs.openframe-frontend-core }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            java:
              - 'pom.xml'
              - 'openframe-*/**'
              - 'sdk/**'
              - '.mvn/**'
            openframe-frontend-core:
              - 'openframe-frontend-core/**'
