name: Generate Changes

on:
  workflow_call:
    outputs:
      java:
        value: ${{ jobs.changes.outputs.java }}
      openframe-frontend-core:
        value: ${{ jobs.changes.outputs.openframe-frontend-core }}


jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      openframe-frontend-core: ${{ steps.filter.outputs.openframe-frontend-core }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            java:
              - 'pom.xml'
              - 'openframe-api-lib/**'
              - 'openframe-api-service-core/**'
              - 'openframe-authorization-service-core/**'
              - 'openframe-client-core/**'
              - 'openframe-config-core/**'
              - 'openframe-core/**'
              - 'openframe-data-kafka/**'
              - 'openframe-data-mongo/**'
              - 'openframe-data/**'
              - 'openframe-external-api-service-core/**'
              - 'openframe-gateway-service-core/**'
              - 'openframe-idp-configuration/**'
              - 'openframe-management-service-core/**'
              - 'openframe-notification-mail/**'
              - 'openframe-security-core/**'
              - 'openframe-security-oauth/**'
              - 'openframe-stream-service-core/**'
              - 'sdk/**'
              - '.mvn/**'
            openframe-frontend-core:
              - 'openframe-frontend-core/**'
